#checks if the inverse has already been calculated for a cahced matrix, if so return cached value, else, it calculates it. 
cachesolve <- function(x, ...) {
        #cachesolve will use the output list generated by makeCacheMatrix.R, this list has a sqaure matrix, its inverse
        #the operation used to get the inverse (solve), and a variable describing if the operation has allready been 
        #performed, i which is null if it has.
        i <- x$getsolve()
        #gets the solve status (either null, if it hasnt been inversed or the inverse, if it has)
        if(!is.null(i)) {
                #if i is null, then the inverse has been calculated and cached data is obtained
                message("getting cached data")
                #terminates the function
                return(i)
        }
        #if has been solved, it gets the matrix in "data"
        data <- x$get()
        #inverses it
        i <- solve(data, ...)
        #makes getsolve the inverse so that next time the inverse is not calculated but obtained from cache
        x$setsolve(i)
        i
}
